### ISSUE TITLE
Abrir DF en impresora fiscal

### ISSUE THREAD

**Issue by androetto** [codermapuche/hasar-fp#3]
Estimados, tengo un problema cuando ejecuto el programa me dice ERROR funcion no soportada de controlador fiscal seleccionada abrir df en impresora fiscal. Alguien sabe que me esta faltando?

**Comment by codermapuche** [comment]
Podrías mostar que código estas ejecutando? la descripción corresponde al error IMPRESOR_FISCAL_ERROR_NO_IMPLEMENTADO lo que indica que lo que quieres hacer no esta soportado por el modelo en cuestión.

Te sugiero que primero emitas un repote X para asegurarte que todo esta andando antes de emitir un DF.
